version: '3.8'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: psyntify
      POSTGRES_USER: psyntify
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - psyntify_pg_data:/var/lib/postgresql/data

volumes:
  psyntify_pg_data:
