spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/psyntify
    username: psyntify
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
